version: '3.1'

services:
  db:
    container_name: influx_db_1
    image: influxdb:1.7-alpine
    restart: unless-stopped
    command: influxd -config /config/influxdb.conf
    ports:
      - ${PORT:-8086}:8086
      - ${PORT_ADMIN:-8083}:8083
      - ${PORT_GRAPHITE:-2003}:2003
    environment:
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER:-admin}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD:-password}
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_REPORTING_DISABLED=true
      - INFLUXDB_GRAPHITE_ENABLED=false

    volumes:
      - ./config:/config
      - ./data:/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
