version: '3.1'

services:
  db:
    container_name: grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    user: "0:0" # user's UID:GID
    ports:
      - ${PORT:-1313}:3000
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - ./data:/var/lib/grafana:delegated
