version: '3.5'

services:
  server:
    container_name: ssh_server_1
    image: dotslashlabs/amzlinux2-vm:latest
    restart: unless-stopped
    privileged: true
    ports:
      - ${PORT_SSH:-7022}:22
      - ${PORT_HTTP:-80}:80
      - ${PORT_HTTPS:-443}:443
    networks:
      - docker-net

  docker:
    container_name: ssh_dind_1
    image: docker:18.06.3-ce-dind
    restart: unless-stopped
    privileged: true
    volumes:
      - /var/lib/docker
    networks:
      - docker-net

networks:
  docker-net:
    driver: bridge
