version: '3.1'

services:
  db:
    container_name: postgres_db_1
    image: postgres:11-alpine
    restart: unless-stopped
    command: postgres -c config_file=/config/postgresql.conf -c hba_file=/config/pg_hba.conf
    ports:
      - ${PORT:-5432}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - PRODUCT_DB=${PRODUCT_DB:-product}
      - PRODUCT_DB_USER=${PRODUCT_DB_USER:-product}
      - PRODUCT_DB_PASSWORD=${PRODUCT_DB_PASSWORD:-password}
    volumes:
      - ./config:/config
      - ./data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
