version: '3.1'

services:
  db:
    container_name: mongo_db_1
    image: mongo:4
    restart: unless-stopped
    command: mongod --auth --bind_ip_all --config /config/mongod.conf
    ports:
      - ${PORT:-27017}:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:-password}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE:-db}
    volumes:
      - ./config:/config
      - ./data/db:/data/db
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
