version: '3.1'

services:
  server:
    container_name: redis_server_1
    image: redis:5-alpine
    restart: unless-stopped
    command: redis-server /config/redis.conf
    ports:
      - ${PORT:-6379}:6379
    volumes:
      - ./config:/config
      - ./data:/data
